# Generated by Django 4.0.1 on 2022-02-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='seccion_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_1', models.CharField(max_length=100)),
                ('titulo_2', models.CharField(max_length=100)),
                ('titulo_3', models.CharField(max_length=100)),
                ('imagen', models.ImageField(null=True, upload_to='img_seccion_1')),
            ],
        ),
        migrations.CreateModel(
            name='smart_cash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(null=True, upload_to='')),
                ('encabezado', models.CharField(max_length=100)),
                ('informacion', models.CharField(max_length=100)),
                ('hipervinculo', models.URLField()),
                ('imagen', models.ImageField(null=True, upload_to='img_smart_cash')),
            ],
        ),
        migrations.CreateModel(
            name='wealth_management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(null=True, upload_to='')),
                ('encabezado', models.TextField(max_length=100)),
                ('informacion', models.TextField(max_length=100)),
                ('hipervinculo', models.URLField()),
                ('javascripts', models.TextField()),
                ('listadesplegable', models.TextField()),
            ],
        ),
    ]
