# Generated by Django 4.0.1 on 2022-03-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgbm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='planes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Titulo',
                'verbose_name_plural': 'Titulos',
            },
        ),
        migrations.AlterModelOptions(
            name='seccion_1',
            options={'verbose_name': 'Titulo', 'verbose_name_plural': 'Titulos'},
        ),
        migrations.AlterModelOptions(
            name='smart_cash',
            options={'verbose_name': 'Tipo de Plan', 'verbose_name_plural': 'Smart Cash'},
        ),
        migrations.AlterModelOptions(
            name='wealth_management',
            options={'verbose_name': 'Tipo de Plan', 'verbose_name_plural': 'Wealth Management'},
        ),
    ]
