# Generated by Django 4.0.1 on 2022-03-02 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appgbm', '0002_planes_alter_seccion_1_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seccion_1',
            options={'verbose_name': 'Seccion 1', 'verbose_name_plural': 'Titulos'},
        ),
    ]
