# Generated by Django 4.0.1 on 2022-03-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgbm', '0003_alter_seccion_1_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='seccion_1',
        ),
        migrations.AlterModelOptions(
            name='planes',
            options={'verbose_name': 'Plan', 'verbose_name_plural': 'Planes'},
        ),
        migrations.AddField(
            model_name='planes',
            name='descripcion',
            field=models.TextField(default='Ups tenemos un problema'),
        ),
    ]
