# Generated by Django 4.0.1 on 2022-03-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgbm', '0005_planes_icono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto_footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta', models.TextField(max_length=80)),
                ('correo_e', models.TextField(max_length=80)),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
            },
        ),
    ]
