# Generated by Django 4.0.3 on 2022-04-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgbm', '0006_contacto_footer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto_footer',
            name='correo_e',
            field=models.EmailField(max_length=80),
        ),
    ]
