# Generated by Django 4.0.3 on 2022-04-22 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgbm', '0007_alter_contacto_footer_correo_e'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios_inicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.CharField(max_length=80)),
                ('comentario', models.TextField(max_length=280)),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
            },
        ),
    ]
