# Generated by Django 4.0.3 on 2022-04-23 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appgbm', '0008_comentarios_inicio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='smart_cash',
        ),
        migrations.DeleteModel(
            name='wealth_management',
        ),
    ]
