# Generated by Django 4.0.3 on 2022-04-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgbm', '0009_delete_smart_cash_delete_wealth_management'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=80)),
                ('usuario', models.CharField(max_length=80)),
                ('correo_e', models.EmailField(max_length=100)),
                ('contraseña', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
